#!groovy​
package com.github.jvanheesch.temp

@Library('jenkins-shared-library')

def pom

pipeline {
    agent {
        label 'master'
    }

    options {
        disableConcurrentBuilds()
    }

    tools {
        maven 'jenkins-maven-installation-3.5.4'
    }

    stages {
//        https://jenkins.io/blog/2017/02/07/declarative-maven-project/
        stage('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
        stage('Maven Testing') {
            steps {
                timestamps {
                    script {
                        sh 'mvn -version'
                    }
                }
            }
        }
    }
    post {
        failure {
            script {
                echo "FAILURE"
            }
        }
    }
}