#!groovy​
package com.github.jvanheesch.sitedeploy

@Library('jenkins-shared-library')
import static com.github.jvanheesch.shared.HelperGroovy.*

def pom

pipeline {
    agent {
        label 'master'
    }

    options {
        disableConcurrentBuilds()
    }

    parameters {
        string(description: 'Version', name: 'TAG_VERSION')
    }

    stages {
        stage('Checkout') {
            steps {
                timestamps {
                    script {
//                        checkoutFromGithubWithTag(this, 'site-parent-pom', master, "site-parent-pom-${params.TAG_VERSION}")
                        checkoutFromGithub(this, 'site-parent-pom', master)
                        pom = this.readMavenPom()
                    }
                }
            }
        }
        stage('Build') {
            steps {
                timestamps {
                    script {
                        echo 'Build'
                        sh 'mvn clean install -U -DskipTests=true'
                    }
                }
            }
        }
    }
    post {
        failure {
            script {
                echo 'Failure'
            }
        }
    }
}