#!groovy​
package com.github.jvanheesch.sitedeploy

@Library('jenkins-shared-library')
import static com.github.jvanheesch.shared.HelperGroovy.*

def pom

pipeline {
    agent {
        label 'master'
    }

    options {
        disableConcurrentBuilds()
    }

    parameters {
        string(description: 'Version', name: 'TAG_VERSION')
    }

    stages {
        stage('Checkout') {
            steps {
                timestamps {
                    script {
                        echo artifactId + "${params.TAG_VERSION}"
                        checkoutFromGithubWithTag(this, 'site-parent-pom', artifactId + "-${params.TAG_VERSION}")
                        pom = this.readMavenPom()
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                timestamps {
                        script {
                            sh 'mvn clean deploy -U -DskipTests=true'
                    }
                }
            }
        }
    }
    post {
        failure {
            script {
                echo "FAILURE"
            }
        }
    }
}