#!groovy​
package com.github.jvanheesch.branchestest

import static com.github.jvanheesch.branchestest.TestConstants.scmGroupName

def pom

pipeline {
    agent {
        label 'master'
    }

    options {
        disableConcurrentBuilds()
    }

    tools {
        maven 'jenkins-maven-installation-3.5.4'
    }

    stages {
        stage('Checkout') {
            steps {
                timestamps {
                    script {
                        echo "constant"
                        echo scmGroupName
                    }
                }
            }
        }
    }
    post {
        failure {
            script {
                echo "FAILURE"
            }
        }
    }
}